CREATE TABLE IF NOT EXISTS eleitores (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    cpf VARCHAR(50) NOT NULL UNIQUE,
    titulo_eleitor VARCHAR(12) NOT NULL UNIQUE,
    mesario BOOLEAN NOT NULL,
    chave_acesso VARCHAR(50) NOT NULL,
    status_voto VARCHAR(20) DEFAULT 'Não votou'
);

CREATE TABLE IF NOT EXISTS candidatos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    numero INT NOT NULL UNIQUE,
    partido VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS votos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_candidato INT,
    data_hora TIMESTAMP NOT NULL,
    protocolo VARCHAR(100) NOT NULL,
    FOREIGN KEY (id_candidato) REFERENCES candidatos(id)
);

CREATE TABLE IF NOT EXISTS urna (
    id INT AUTO_INCREMENT PRIMARY KEY,
    status VARCHAR(20) NOT NULL,
    data_abertura DATETIME NOT NULL,
    data_encerramento DATETIME
);

CREATE TABLE IF NOT EXISTS logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    data_hora DATETIME NOT NULL,
    evento VARCHAR(255) NOT NULL
);

